apiVersion: v1
kind: Service
metadata:
 name: gcp-server-service
 labels:
   name: gcp-server-service
   app: grpc-server-app
spec:
 type: LoadBalancer
 ports:
 - port: 50051
   targetPort: 50051
 selector:
    name: server-pod
    app: grpc-server-app